# URL de conexi\u00f3n a MongoDB
quarkus.mongodb.connection-string=mongodb+srv://admin:admin@apimatriculauii.qu5phyu.mongodb.net/?retryWrites=true&w=majority";

# Nombre de la base de datos
quarkus.mongodb.database=APImatriculauii

